version: "3.9"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_SECURE=${SMTP_SECURE}
      - MAIL_TO=${MAIL_TO}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - TRUST_PROXY=${TRUST_PROXY}
